# Generated by Django 4.1 on 2024-03-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FdClassForest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sup', models.CharField(blank=True, max_length=255, null=True)),
                ('sub', models.TextField(blank=True, null=True)),
                ('info', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'fd_class_forest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FdEntity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('entity', models.CharField(max_length=100)),
                ('imgurl', models.CharField(blank=True, db_column='imgUrl', max_length=255, null=True)),
                ('relatedtype', models.TextField(blank=True, db_column='relatedType', null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fd_entity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FdRelation',
            fields=[
                ('id_s', models.IntegerField(db_column='id_S', primary_key=True, serialize=False)),
                ('s', models.CharField(db_column='S', max_length=100)),
                ('p', models.CharField(db_column='P', max_length=100)),
                ('o', models.CharField(db_column='O', max_length=100)),
                ('id_o', models.IntegerField(db_column='id_O')),
            ],
            options={
                'db_table': 'fd_relation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SelfEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(blank=True, max_length=255, null=True)),
                ('imgurl', models.CharField(blank=True, db_column='imgUrl', max_length=255, null=True)),
                ('relatedtype', models.CharField(blank=True, db_column='relatedType', max_length=255, null=True)),
                ('abstract', models.CharField(blank=True, max_length=255, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.IntegerField()),
                ('graph_id', models.IntegerField()),
                ('entity_id', models.IntegerField()),
            ],
            options={
                'db_table': 'self.entity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SelfGraphInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('graph_id', models.IntegerField()),
                ('graph_name', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.IntegerField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'self_graph_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SelfRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('graph_id', models.IntegerField()),
                ('id_s', models.IntegerField(blank=True, db_column='id_S', null=True)),
                ('s', models.CharField(blank=True, db_column='S', max_length=255, null=True)),
                ('p', models.CharField(blank=True, db_column='P', max_length=255, null=True)),
                ('o', models.CharField(blank=True, db_column='O', max_length=255, null=True)),
                ('id_o', models.IntegerField(blank=True, db_column='id_O', null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'self.relation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
