# Generated by Django 4.1.1 on 2024-03-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FdTop5",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("top1_id", models.IntegerField(blank=True, null=True)),
                ("value1", models.FloatField(blank=True, null=True)),
                ("top2_id", models.IntegerField(blank=True, null=True)),
                ("value2", models.FloatField(blank=True, null=True)),
                ("top3_id", models.IntegerField(blank=True, null=True)),
                ("value3", models.FloatField(blank=True, null=True)),
                ("top4_id", models.IntegerField(blank=True, null=True)),
                ("value4", models.FloatField(blank=True, null=True)),
                ("top5_id", models.IntegerField(blank=True, null=True)),
                ("value5", models.FloatField(blank=True, null=True)),
            ],
            options={"db_table": "fd_top5", "managed": False,},
        ),
        migrations.AlterModelTable(name="selfentity", table="self_entity",),
        migrations.AlterModelTable(name="selfrelation", table="self_relation",),
    ]
